#ifndef _JUICTRLMISC_H_
#define _JUICTRLMISC_H_
#pragma once


//@ 대화상자
enum eSKINTYPE_DIALOG
{
	eSKINTYPE_DIALOG_BACKGROUND,
	eSKINTYPE_DIALOG_MAX
};

//@ 스태틱
enum eSKINTYPE_STATIC
{
	eSKINTYPE_STATIC_BACKGROUND,
	eSKINTYPE_STATIC_MAX
};

//@ 버튼
enum eSKINTYPE_BUTTON
{
	eSKINTYPE_BUTTON_ACTIVE,
	eSKINTYPE_BUTTON_MOUSEOVER,
	eSKINTYPE_BUTTON_CLICKED,
	eSKINTYPE_BUTTON_UNACTIVE,
	eSKINTYPE_BUTTON_MAX
};

//@ 체크박스
enum eSKINTYPE_CHECKBOX
{
	//@ 체크된 상태
	eSKINTYPE_CHECKBOX_CHCK_ACTIVE,		
	eSKINTYPE_CHECKBOX_CHCK_MOUSEOVER,
	eSKINTYPE_CHECKBOX_CHCK_CLICKED,
	eSKINTYPE_CHECKBOX_CHCK_UNACTIVE,

	//@ 체크되지 않은 상태
	eSKINTYPE_CHECKBOX_UNCHCK_ACTIVE,
	eSKINTYPE_CHECKBOX_UNCHCK_MOUSEOVER,
	eSKINTYPE_CHECKBOX_UNCHCK_CLICKED,
	eSKINTYPE_CHECKBOX_UNCHCK_UNACTIVE,

	eSKINTYPE_CHECKBOX_MAX
};

//@ 라디오 버튼
enum eSKINTYPE_RADIOBUTTON
{
	eSKINTYPE_RADIOBUTTON_CHCK_ACTIVE,
	eSKINTYPE_RADIOBUTTON_CHCK_MOUSEOVER,
	eSKINTYPE_RADIOBUTTON_CHCK_CLICKED,
	eSKINTYPE_RADIOBUTTON_CHCK_UNACTIVE,

	eSKINTYPE_RADIOBUTTON_UNCHCK_ACTIVE,
	eSKINTYPE_RADIOBUTTON_UNCHCK_MOUSEOVER,
	eSKINTYPE_RADIOBUTTON_UNCHCK_CLICKED,
	eSKINTYPE_RADIOBUTTON_UNCHCK_UNACTIVE,

	eSKINTYPE_RADIOBUTTON_MAX
};

//@ 콤보박스
enum eSKINTYPE_COMBOBOX
{
	eSKINTYPE_COMBOBOX_EDITBOX,
	eSKINTYPE_COMBOBOX_DROPDOWNBOX,
	eSKINTYPE_COMBOBOX_SELECTION,
	eSKINTYPE_COMBOBOX_ACTIVEBTN,
	eSKINTYPE_COMBOBOX_MOUSEOVERBTN,
	eSKINTYPE_COMBOBOX_CLICKEDBTN,
	eSKINTYPE_COMBOBOX_MAX
};

//@ 스크롤 바
enum eSKINTYPE_SCROLLBAR
{
	eSKINTYPE_SCROLLBAR_TRACKBAR,

	eSKINTYPE_SCROLLBAR_PREBTN_ACTIVE,
	eSKINTYPE_SCROLLBAR_PREBTN_MOUSEOVER,
	eSKINTYPE_SCROLLBAR_PREBTN_CLICKED,

	eSKINTYPE_SCROLLBAR_NEXTBTN_ACTIVE,
	eSKINTYPE_SCROLLBAR_NEXTBTN_MOUSEOVER,
	eSKINTYPE_SCROLLBAR_NEXTBTN_CLICKED,

	eSKINTYPE_SCROLLBAR_THUMBBTN_ACTIVE,
	eSKINTYPE_SCROLLBAR_THUMBBTN_MOUSEOVER,
	eSKINTYPE_SCROLLBAR_THUMBBTN_CLICKED,

	eSKINTYPE_SCROLLBAR_MAX
};

//@ 슬라이더
enum eSKINTYPE_SLIDER
{
	eSKINTYPE_SLIDER_TRACK,

	eSKINTYPE_SLIDER_BTN_ACTIVE,
	eSKINTYPE_SLIDER_BTN_MOUSEOVER,
	eSKINTYPE_SLIDER_BTN_CLICKED,
	eSKINTYPE_SLIDER_BTN_UNACTIVE,

	eSKINTYPE_SLIDER_MAX
};

//@ 리스트 박스
enum eSKINTYPE_LISTBOX
{
	eSKINTYPE_LISTBOX_BACKGROUND,
	eSKINTYPE_LISTBOX_SELECT,
	eSKINTYPE_LISTBOX_MAX
};

//@ 에디트 박스
enum eSKINTYPE_EDITBOX
{
	eSKINTYPE_EDITBOX_BACKGROUND,
	eSKINTYPE_EDITBOX_MAX
};

#endif	//	_JUICTRLMISC_H_